module.exports = async(sock, m, prefix, command, setQuoted) => {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("1seconds")}`, description: `${command.toUpperCase()} 1 ${mess.time.seconds.toUpperCase()}`},
{title: `2 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("2seconds")}`, description: `${command.toUpperCase()} 2 ${mess.time.seconds.toUpperCase()}`},
{title: `3 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("3seconds")}`, description: `${command.toUpperCase()} 3 ${mess.time.seconds.toUpperCase()}`},
{title: `4 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("4seconds")}`, description: `${command.toUpperCase()} 4 ${mess.time.seconds.toUpperCase()}`},
{title: `5 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("5seconds")}`, description: `${command.toUpperCase()} 5 ${mess.time.seconds.toUpperCase()}`},
{title: `6 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("6seconds")}`, description: `${command.toUpperCase()} 6 ${mess.time.seconds.toUpperCase()}`},
{title: `7 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("7seconds")}`, description: `${command.toUpperCase()} 7 ${mess.time.seconds.toUpperCase()}`},
{title: `8 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("8seconds")}`, description: `${command.toUpperCase()} 8 ${mess.time.seconds.toUpperCase()}`},
{title: `9 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("9seconds")}`, description: `${command.toUpperCase()} 9 ${mess.time.seconds.toUpperCase()}`},
{title: `10 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("10seconds")}`, description: `${command.toUpperCase()} 10 ${mess.time.seconds.toUpperCase()}`},
{title: `11 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("11seconds")}`, description: `${command.toUpperCase()} 11 ${mess.time.seconds.toUpperCase()}`},
{title: `12 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("12seconds")}`, description: `${command.toUpperCase()} 12 ${mess.time.seconds.toUpperCase()}`},
{title: `13 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("13seconds")}`, description: `${command.toUpperCase()} 13 ${mess.time.seconds.toUpperCase()}`},
{title: `14 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("14seconds")}`, description: `${command.toUpperCase()} 14 ${mess.time.seconds.toUpperCase()}`},
{title: `15 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("15seconds")}`, description: `${command.toUpperCase()} 15 ${mess.time.seconds.toUpperCase()}`},
{title: `16 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("16seconds")}`, description: `${command.toUpperCase()} 16 ${mess.time.seconds.toUpperCase()}`},
{title: `17 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("17seconds")}`, description: `${command.toUpperCase()} 17 ${mess.time.seconds.toUpperCase()}`},
{title: `18 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("18seconds")}`, description: `${command.toUpperCase()} 18 ${mess.time.seconds.toUpperCase()}`},
{title: `19 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("19seconds")}`, description: `${command.toUpperCase()} 19 ${mess.time.seconds.toUpperCase()}`},
{title: `20 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("20seconds")}`, description: `${command.toUpperCase()} 20 ${mess.time.seconds.toUpperCase()}`},
{title: `21 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("21seconds")}`, description: `${command.toUpperCase()} 21 ${mess.time.seconds.toUpperCase()}`},
{title: `22 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("22seconds")}`, description: `${command.toUpperCase()} 22 ${mess.time.seconds.toUpperCase()}`},
{title: `23 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("23seconds")}`, description: `${command.toUpperCase()} 23 ${mess.time.seconds.toUpperCase()}`},
{title: `24 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("24seconds")}`, description: `${command.toUpperCase()} 24 ${mess.time.seconds.toUpperCase()}`},
{title: `25 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("25seconds")}`, description: `${command.toUpperCase()} 25 ${mess.time.seconds.toUpperCase()}`},
{title: `26 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("26seconds")}`, description: `${command.toUpperCase()} 26 ${mess.time.seconds.toUpperCase()}`},
{title: `27 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("27seconds")}`, description: `${command.toUpperCase()} 27 ${mess.time.seconds.toUpperCase()}`},
{title: `28 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("28seconds")}`, description: `${command.toUpperCase()} 28 ${mess.time.seconds.toUpperCase()}`},
{title: `29 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("29seconds")}`, description: `${command.toUpperCase()} 29 ${mess.time.seconds.toUpperCase()}`},
{title: `30 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("30seconds")}`, description: `${command.toUpperCase()} 30 ${mess.time.seconds.toUpperCase()}`},
{title: `31 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("31seconds")}`, description: `${command.toUpperCase()} 31 ${mess.time.seconds.toUpperCase()}`},
{title: `32 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("32seconds")}`, description: `${command.toUpperCase()} 32 ${mess.time.seconds.toUpperCase()}`},
{title: `33 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("33seconds")}`, description: `${command.toUpperCase()} 33 ${mess.time.seconds.toUpperCase()}`},
{title: `34 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("34seconds")}`, description: `${command.toUpperCase()} 34 ${mess.time.seconds.toUpperCase()}`},
{title: `35 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("35seconds")}`, description: `${command.toUpperCase()} 35 ${mess.time.seconds.toUpperCase()}`},
{title: `36 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("36seconds")}`, description: `${command.toUpperCase()} 36 ${mess.time.seconds.toUpperCase()}`},
{title: `37 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("37seconds")}`, description: `${command.toUpperCase()} 37 ${mess.time.seconds.toUpperCase()}`},
{title: `38 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("38seconds")}`, description: `${command.toUpperCase()} 38 ${mess.time.seconds.toUpperCase()}`},
{title: `39 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("39seconds")}`, description: `${command.toUpperCase()} 39 ${mess.time.seconds.toUpperCase()}`},
{title: `40 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("40seconds")}`, description: `${command.toUpperCase()} 40 ${mess.time.seconds.toUpperCase()}`},
{title: `41 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("41seconds")}`, description: `${command.toUpperCase()} 41 ${mess.time.seconds.toUpperCase()}`},
{title: `42 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("42seconds")}`, description: `${command.toUpperCase()} 42 ${mess.time.seconds.toUpperCase()}`},
{title: `43 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("43seconds")}`, description: `${command.toUpperCase()} 43 ${mess.time.seconds.toUpperCase()}`},
{title: `44 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("44seconds")}`, description: `${command.toUpperCase()} 44 ${mess.time.seconds.toUpperCase()}`},
{title: `45 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("45seconds")}`, description: `${command.toUpperCase()} 45 ${mess.time.seconds.toUpperCase()}`},
{title: `46 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("46seconds")}`, description: `${command.toUpperCase()} 46 ${mess.time.seconds.toUpperCase()}`},
{title: `47 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("47seconds")}`, description: `${command.toUpperCase()} 47 ${mess.time.seconds.toUpperCase()}`},
{title: `48 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("48seconds")}`, description: `${command.toUpperCase()} 48 ${mess.time.seconds.toUpperCase()}`},
{title: `49 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("49seconds")}`, description: `${command.toUpperCase()} 49 ${mess.time.seconds.toUpperCase()}`},
{title: `50 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("50seconds")}`, description: `${command.toUpperCase()} 50 ${mess.time.seconds.toUpperCase()}`},
{title: `51 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("51seconds")}`, description: `${command.toUpperCase()} 51 ${mess.time.seconds.toUpperCase()}`},
{title: `52 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("52seconds")}`, description: `${command.toUpperCase()} 52 ${mess.time.seconds.toUpperCase()}`},
{title: `53 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("53seconds")}`, description: `${command.toUpperCase()} 53 ${mess.time.seconds.toUpperCase()}`},
{title: `54 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("54seconds")}`, description: `${command.toUpperCase()} 54 ${mess.time.seconds.toUpperCase()}`},
{title: `55 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("55seconds")}`, description: `${command.toUpperCase()} 55 ${mess.time.seconds.toUpperCase()}`},
{title: `56 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("56seconds")}`, description: `${command.toUpperCase()} 56 ${mess.time.seconds.toUpperCase()}`},
{title: `57 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("57seconds")}`, description: `${command.toUpperCase()} 57 ${mess.time.seconds.toUpperCase()}`},
{title: `58 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("58seconds")}`, description: `${command.toUpperCase()} 58 ${mess.time.seconds.toUpperCase()}`},
{title: `59 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("59seconds")}`, description: `${command.toUpperCase()} 59 ${mess.time.seconds.toUpperCase()}`},
{title: `60 ${mess.time.seconds.toUpperCase()}`, rowId: `${prefix + command} seconds ${toMs("60seconds")}`, description: `${command.toUpperCase()} 60 ${mess.time.seconds.toUpperCase()}`},
]}]
const listMessage = { text: `${command.toUpperCase()} ${mess.time.seconds.toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: setQuoted })
}