module.exports = async(sock, m, prefix, command, setQuoted) => {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("1minutes")}`, description: `${command.toUpperCase()} 1 ${mess.time.minutes.toUpperCase()}`},
{title: `2 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("2minutes")}`, description: `${command.toUpperCase()} 2 ${mess.time.minutes.toUpperCase()}`},
{title: `3 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("3minutes")}`, description: `${command.toUpperCase()} 3 ${mess.time.minutes.toUpperCase()}`},
{title: `4 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("4minutes")}`, description: `${command.toUpperCase()} 4 ${mess.time.minutes.toUpperCase()}`},
{title: `5 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("5minutes")}`, description: `${command.toUpperCase()} 5 ${mess.time.minutes.toUpperCase()}`},
{title: `6 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("6minutes")}`, description: `${command.toUpperCase()} 6 ${mess.time.minutes.toUpperCase()}`},
{title: `7 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("7minutes")}`, description: `${command.toUpperCase()} 7 ${mess.time.minutes.toUpperCase()}`},
{title: `8 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("8minutes")}`, description: `${command.toUpperCase()} 8 ${mess.time.minutes.toUpperCase()}`},
{title: `9 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("9minutes")}`, description: `${command.toUpperCase()} 9 ${mess.time.minutes.toUpperCase()}`},
{title: `10 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("10minutes")}`, description: `${command.toUpperCase()} 10 ${mess.time.minutes.toUpperCase()}`},
{title: `11 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("11minutes")}`, description: `${command.toUpperCase()} 11 ${mess.time.minutes.toUpperCase()}`},
{title: `12 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("12minutes")}`, description: `${command.toUpperCase()} 12 ${mess.time.minutes.toUpperCase()}`},
{title: `13 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("13minutes")}`, description: `${command.toUpperCase()} 13 ${mess.time.minutes.toUpperCase()}`},
{title: `14 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("14minutes")}`, description: `${command.toUpperCase()} 14 ${mess.time.minutes.toUpperCase()}`},
{title: `15 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("15minutes")}`, description: `${command.toUpperCase()} 15 ${mess.time.minutes.toUpperCase()}`},
{title: `16 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("16minutes")}`, description: `${command.toUpperCase()} 16 ${mess.time.minutes.toUpperCase()}`},
{title: `17 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("17minutes")}`, description: `${command.toUpperCase()} 17 ${mess.time.minutes.toUpperCase()}`},
{title: `18 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("18minutes")}`, description: `${command.toUpperCase()} 18 ${mess.time.minutes.toUpperCase()}`},
{title: `19 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("19minutes")}`, description: `${command.toUpperCase()} 19 ${mess.time.minutes.toUpperCase()}`},
{title: `20 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("20minutes")}`, description: `${command.toUpperCase()} 20 ${mess.time.minutes.toUpperCase()}`},
{title: `21 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("21minutes")}`, description: `${command.toUpperCase()} 21 ${mess.time.minutes.toUpperCase()}`},
{title: `22 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("22minutes")}`, description: `${command.toUpperCase()} 22 ${mess.time.minutes.toUpperCase()}`},
{title: `23 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("23minutes")}`, description: `${command.toUpperCase()} 23 ${mess.time.minutes.toUpperCase()}`},
{title: `24 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("24minutes")}`, description: `${command.toUpperCase()} 24 ${mess.time.minutes.toUpperCase()}`},
{title: `25 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("25minutes")}`, description: `${command.toUpperCase()} 25 ${mess.time.minutes.toUpperCase()}`},
{title: `26 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("26minutes")}`, description: `${command.toUpperCase()} 26 ${mess.time.minutes.toUpperCase()}`},
{title: `27 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("27minutes")}`, description: `${command.toUpperCase()} 27 ${mess.time.minutes.toUpperCase()}`},
{title: `28 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("28minutes")}`, description: `${command.toUpperCase()} 28 ${mess.time.minutes.toUpperCase()}`},
{title: `29 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("29minutes")}`, description: `${command.toUpperCase()} 29 ${mess.time.minutes.toUpperCase()}`},
{title: `30 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("30minutes")}`, description: `${command.toUpperCase()} 30 ${mess.time.minutes.toUpperCase()}`},
{title: `31 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("31minutes")}`, description: `${command.toUpperCase()} 31 ${mess.time.minutes.toUpperCase()}`},
{title: `32 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("32minutes")}`, description: `${command.toUpperCase()} 32 ${mess.time.minutes.toUpperCase()}`},
{title: `33 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("33minutes")}`, description: `${command.toUpperCase()} 33 ${mess.time.minutes.toUpperCase()}`},
{title: `34 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("34minutes")}`, description: `${command.toUpperCase()} 34 ${mess.time.minutes.toUpperCase()}`},
{title: `35 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("35minutes")}`, description: `${command.toUpperCase()} 35 ${mess.time.minutes.toUpperCase()}`},
{title: `36 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("36minutes")}`, description: `${command.toUpperCase()} 36 ${mess.time.minutes.toUpperCase()}`},
{title: `37 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("37minutes")}`, description: `${command.toUpperCase()} 37 ${mess.time.minutes.toUpperCase()}`},
{title: `38 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("38minutes")}`, description: `${command.toUpperCase()} 38 ${mess.time.minutes.toUpperCase()}`},
{title: `39 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("39minutes")}`, description: `${command.toUpperCase()} 39 ${mess.time.minutes.toUpperCase()}`},
{title: `40 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("40minutes")}`, description: `${command.toUpperCase()} 40 ${mess.time.minutes.toUpperCase()}`},
{title: `41 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("41minutes")}`, description: `${command.toUpperCase()} 41 ${mess.time.minutes.toUpperCase()}`},
{title: `42 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("42minutes")}`, description: `${command.toUpperCase()} 42 ${mess.time.minutes.toUpperCase()}`},
{title: `43 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("43minutes")}`, description: `${command.toUpperCase()} 43 ${mess.time.minutes.toUpperCase()}`},
{title: `44 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("44minutes")}`, description: `${command.toUpperCase()} 44 ${mess.time.minutes.toUpperCase()}`},
{title: `45 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("45minutes")}`, description: `${command.toUpperCase()} 45 ${mess.time.minutes.toUpperCase()}`},
{title: `46 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("46minutes")}`, description: `${command.toUpperCase()} 46 ${mess.time.minutes.toUpperCase()}`},
{title: `47 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("47minutes")}`, description: `${command.toUpperCase()} 47 ${mess.time.minutes.toUpperCase()}`},
{title: `48 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("48minutes")}`, description: `${command.toUpperCase()} 48 ${mess.time.minutes.toUpperCase()}`},
{title: `49 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("49minutes")}`, description: `${command.toUpperCase()} 49 ${mess.time.minutes.toUpperCase()}`},
{title: `50 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("50minutes")}`, description: `${command.toUpperCase()} 50 ${mess.time.minutes.toUpperCase()}`},
{title: `51 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("51minutes")}`, description: `${command.toUpperCase()} 51 ${mess.time.minutes.toUpperCase()}`},
{title: `52 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("52minutes")}`, description: `${command.toUpperCase()} 52 ${mess.time.minutes.toUpperCase()}`},
{title: `53 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("53minutes")}`, description: `${command.toUpperCase()} 53 ${mess.time.minutes.toUpperCase()}`},
{title: `54 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("54minutes")}`, description: `${command.toUpperCase()} 54 ${mess.time.minutes.toUpperCase()}`},
{title: `55 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("55minutes")}`, description: `${command.toUpperCase()} 55 ${mess.time.minutes.toUpperCase()}`},
{title: `56 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("56minutes")}`, description: `${command.toUpperCase()} 56 ${mess.time.minutes.toUpperCase()}`},
{title: `57 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("57minutes")}`, description: `${command.toUpperCase()} 57 ${mess.time.minutes.toUpperCase()}`},
{title: `58 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("58minutes")}`, description: `${command.toUpperCase()} 58 ${mess.time.minutes.toUpperCase()}`},
{title: `59 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("59minutes")}`, description: `${command.toUpperCase()} 59 ${mess.time.minutes.toUpperCase()}`},
{title: `60 ${mess.time.minutes.toUpperCase()}`, rowId: `${prefix + command} minutes ${toMs("60minutes")}`, description: `${command.toUpperCase()} 60 ${mess.time.minutes.toUpperCase()}`},
]}]
const listMessage = { text: `${command.toUpperCase()} ${mess.time.minutes.toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: setQuoted })
}